baseURL = 'https://devilwords.com' 
languageCode = 'en-us'
theme = "JuiceBar"
title = "Denney's Blog"
enableEmoji = true

[params]
author = "Y3un9vj"
description = "My site description"
authorImage = "/images/avatar.jpg"
paginate = 5
Title = "伴眼阴阳"
content = "I'm Denney, nice to meet you(ˊ˘ˋ*)♡"
imageUrl = "/images/profile.jpg"
favicon = "/images/favicon.ico"

# To add a new social icon 
# More social icons can be found in JuiceBar\layouts\partials\svg.html.
[[params.social]]
name = "Github"
url = "https://github.com/BW-Devil/"
[[params.social]]
name = "twitter"
url = "https://twitter.com/Tomtree_Johnson"
[[params.social]]
name = "telegram"
url = "https://t.me/bwfish"
[[params.social]]
name = "email"
url = "mailto:weunknowing@gmail.com"

[taxonomies]
category = "categories"
tag = "tags"

# To add a new navigation link
[[menu.main]]
name = "Archive"
url = "/post"
[[menu.main]]
name = "Categories"
url = "/categories"
[[menu.main]]
name = "About"
url = "/about"

# If using the giscus commenting system
#[params.giscus]
#repo = "ENTER REPO HERE"
#repoID = "ENTER REPO ID HERE"
#category = "ENTER CATEGORY NAME HERE"
#categoryID = "ENTER CATEGORY ID HERE"
#mapping = "og:title"
#reactionsEnabled = "1"
#emitMetadata = "0"
#inputPosition = "bottom"
#lang = "en"
#loading = "lazy"

# Used for outputting the documentation (required).
[outputs]
home = ["HTML", "RSS", "JSON"]